server:
  port: 8080  # Puerto para el API Gateway

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Ruta específica para el Actuator del users-service
        - id: users-service-actuator
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/actuator/**  # Captura rutas específicas de Actuator
          filters:
            - RewritePath=/api/users/actuator/(?<segment>.*), /actuator/${segment}

        # Ruta general para el users-service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**   # Ruta general para los endpoints de users-service
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

        # Ruta específica para el Cards Service
        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/accounts/{accountId}/cards/**  # Captura rutas dinámicas correctamente
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-cards

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
