server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Ruta específica para el cards-service
        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/cards/**  # Evitar conflictos con transactions-service
          filters:
            - RewritePath=/api/cards/(?<segment>.*), /api/cards/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-cards

        # Rutas específicas para el transactions-service
        - id: transactions-service
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
            - Path=/api/transactions/accounts/**  # Asegurarse de que esto coincida con el prefijo en el controlador
          filters:
            - RewritePath=/api/transactions/accounts/(?<segment>.*), /api/transactions/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        # Ruta específica para el Actuator del users-service
        - id: users-service-actuator
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/actuator/**  # Captura rutas específicas de Actuator
          filters:
            - RewritePath=/api/users/actuator/(?<segment>.*), /actuator/${segment}

        # Ruta general para el users-service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/**   # Captura las demás rutas bajo /api/
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
