server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      default-filters:
        - TokenRelay=  # Permite reenviar el token JWT
      routes:
        # Rutas específicas para el Actuator del users-service
        - id: users-service-actuator
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/actuator/**   # Captura rutas de Actuator
          filters:
            - RewritePath=/api/users/actuator/(?<segment>.*), /actuator/${segment}

        # Rutas generales para el users-service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**   # Corrige el Path para incluir el prefijo /api
          filters:
            - TokenRelay=  # Reenvía el token JWT
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

