server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        # Ruta general para enrutar todas las solicitudes de /api/** al users-service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/**   # Captura cualquier ruta con el prefijo /api
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

