server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Ruta específica para el cards-service
        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<segment>.*), /api/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-cards

        # Ruta para obtener todas las actividades de una cuenta
        - id: transactions-service-activity
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
            - Path=/api/transactions/accounts/{id}/activity/**
          filters:
            - RewritePath=/api/transactions/accounts/(?<segment>.*), /api/transactions/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        # Ruta para obtener detalles de una actividad específica
        - id: transactions-service-activity-details
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
            - Path=/api/transactions/accounts/{id}/activity/{transferenceId}
          filters:
            - RewritePath=/api/transactions/accounts/(?<segment>.*), /api/transactions/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        # Ruta para consultar el saldo disponible de una cuenta
        - id: transactions-service-balance
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
            - Path=/api/transactions/accounts/{id}/balance/**
          filters:
            - RewritePath=/api/transactions/accounts/(?<segment>.*), /api/transactions/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        # Ruta para registrar ingresos (transferences)
        - id: transactions-service-transferences
          uri: lb://TRANSACTIONS-SERVICE
          predicates:
            - Path=/api/transactions/accounts/{id}/transferences/**
          filters:
            - RewritePath=/api/transactions/accounts/(?<segment>.*), /api/transactions/accounts/${segment}
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        # Ruta específica para el Actuator del users-service
        - id: users-service-actuator
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/actuator/**
          filters:
            - RewritePath=/api/users/actuator/(?<segment>.*), /actuator/${segment}

        # Ruta general para el users-service
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
