server:
  port: 8085
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-service
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-accounts

        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        - id: cards-service
          uri: lb://cards-service
          predicates:
            - Path=/cards/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-cards

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

