spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dh  # URI del servidor de autenticación
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-users

        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-accounts

        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-transactions

        - id: cards-service
          uri: lb://cards-service
          predicates:
            - Path=/cards/**
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Gateway, response-cards

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL del servidor Eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
